### ISSUE TITLE
How to navigate M-x results and how to display properties/options/commands?

### ISSUE THREAD

**Issue by pintassilgo** [Seme4eg/mpv-scripts#1]
How to navigate results instead of getting stuck on the first one? Tried arrow keys, tab, clicking and some other things, none worked. In first 5 seconds of demo video, I can see lines other than the first one being selected, but cursor cannot be seen.

M-x looks like a better version of [mpv-search-page](https://github.com/CogentRedTester/mpv-search-page/), because M-x filters every char you type, while `mpv-search-page` requires you to press Enter. I also think M-x has better UI. But there are a couple of things I miss from `mpv-search-page`:
- navigate results as said above.
- I don't know if I'm doing something wrong, but it looks like M-x only displays keybinginds, not other things like properties (example: `seekable`), commands (example: `seek`) or options (example: `osd-on-seek`).

**Comment by Seme4eg** [comment]
@pintassilgo , Ctrl-j, ctrl-k are the keybinds you can use to navigate the results.
For full keybindings list that are available you can browse the extended menu script file, they are all there.
I will also update the readme so people don't get confused on that.
The 'M-x' naming basically tells that i made a simplified copy of M-x emacs functionality in mpv, so i assumed that people who will find and use that script will be familiar with M-x bindings already, but i see now i was wrong.
And what about 'all things in one menu'.. i think it's gonna be a mess and as i said above i copied emacs' M-x, which i find it very polished. Putting all things in one menu will make the whole menu slower and thus will require lots of optimizing work. I was thinking about implementing another script for options menu but then i thought that there is no point since you won't be able to change those from menu like you can in emacs.

And sorry for late response, i wasn't expecting any issues and even stars on that repo.

**Comment by Seme4eg** [comment]
Sorry, apparently i already documented the keybindings for the menu here https://github.com/Seme4eg/mpv-scripts/blob/master/script-modules/README.org#L94

**Comment by pintassilgo** [comment]
Thanks for your answer. Ctrl+J/N and Ctrl+K/P aren't working for me to navigate the results, I'll try to understand why.

**Comment by pintassilgo** [comment]
I still have no idea, but this is a stripped down profile in which I can still reproduce the issue:

- No mpv.conf;

- This input.conf entire content:
      
      ctrl+d vf toggle hflip
      ctrl+r vf toggle hflip
      ctrl+m vf toggle hflip
      ctrl+s vf toggle hflip
      ctrl+a vf toggle hflip
      ctrl+q vf toggle hflip


- No other script-module besides extended-menu
- Only one script besides M-x. `tst.lua`:
 
      local function tst()
          mp.osd_message("tst")
      end
      
      mp.add_key_binding("ctrl+x", "tst", tst)

1. Open mpv, press `t` to display M-x interface;
2. Type "ctr" or "ctrl".
3. Press Ctrl+J/N/K/P. Instead of navigate the results, M-x interface just closes.

Steps must be followed carefully. A single missing line in input.conf is enough to not be able to reproduce the error, or the absence of `tst.lua`...

**Comment by stax76** [comment]
Most users are probably not familiar with Emacs and expect and prefer UP/DOWN key to navigate.

It could be addressed in two ways:

1. Support customizing the keys as done by mpv-file-browser:

https://github.com/CogentRedTester/mpv-file-browser

This is very powerful and heavily used by me in mpv-file-browser.

2. Support different binding modes, 'regular', 'emacs', 'vim' etc.

I created fork in order to create a pull request, there I also change the binding to use up/down key.

**Comment by AYehia0** [comment]
I have the same issue, but I think I know where the problem come from : 
this always makes the history_pos = old_pos
```lua
  -- Restrict the position to a legal value
  if self.history_pos > #self.history + 1 then
    self.history_pos = #self.history + 1
  elseif self.history_pos < 1 then
    self.history_pos = 1
  end
```

also, it doesn't highlight after up/down keys are pressed.

**Comment by 2-4601** [comment]
I am also experiencing this exact issue with the symptoms described in earlier posts.

**Comment by Seme4eg** [comment]
Perhaps this is already irrelevant, but i did try step-by-step minimal configuration that @pintassilgo proposed and ctrl-j/k/n/p still work just fine for me. 
Also @AYehia0 guess about history isn't correct as well since for me list traversal back and forth works just fine.
Someone having this problem needs to tell which flags he has mpv built with, are there any errors in his mpv console and if he can do some debugging with prints to the console - up to which point code execution continues. @2-4601, you are the last person who reported having the problem, so i will be grateful if you will help me understand where it comes from. 
FYI i am using the AUR package `mpv-full`, which just builds mpv with all features enabled.

**Comment by hunkyburrito** [comment]
I'm also having issues navigating M-x with keybindings from extended-menu. It seems to be an error within M-x because when using chapter-list it works as expected.

I am using the mpv package from the official Arch repository, and am getting the following error when using `Ctrl+j` or any other list navigating keybinds:
<details>
<summary> Error </summary>

```
[M_x]
[M_x] stack traceback:
[M_x] 	/home/hunky/.config/mpv/script-modules/extended-menu.lua:161: in function 'change_selected_index'
[M_x] 	/home/hunky/.config/mpv/script-modules/extended-menu.lua:822: in function 'fn'
[M_x] 	mp.defaults:230: in function 'fn'
[M_x] 	mp.defaults:65: in function 'handler'
[M_x] 	mp.defaults:382: in function 'handler'
[M_x] 	mp.defaults:512: in function 'call_event_handlers'
[M_x] 	mp.defaults:554: in function 'dispatch_events'
[M_x] 	mp.defaults:505: in function <mp.defaults:504>
[M_x] 	[C]: at 0x61ce8997a430
[M_x] 	[C]: at 0x61ce8997ab10
[M_x] Lua error: /home/hunky/.config/mpv/script-modules/extended-menu.lua:136: attempt to call field 'unpack' (a nil value)
```
</details>

**Comment by Seme4eg** [comment]
@hunkyburrito , installed mpv from aur repos, got same error you reported. I am using AUR mpv-full, which builds with luaJIT hence this 'unpack' method is deprecated there and doesn't work. With this fix i pushed i am no longer getting this error and navigation works, please check and notify me if there are still some issues.
